### ISSUE TITLE
Data from article.

### ISSUE THREAD

**Issue by edkonyakhina** [gacatag/IntEREst#1]
Hello!
If it is possible, could you provide data you used in article? I want to test your program on my computer and understand if I do something wrong, using results from article. Here I mean mutated and WT .bam files.

Many thanks,
Evgeniya

**Comment by gacatag** [comment]
Hi Evgeniya!
Sorry for the late response. I was wondering! Do you still need the .bam files? If so could you kindly contact me via email, I'll have to come up with a method to transfer the files (they are quite large). Please also note that if you wish to map the reads yourself the scripts I used to generate the .bam files are available here: 
https://github.com/gacatag/IntEREst_suppl_data/blob/master/scripts/preprocessing.sh

The accession number of the raw data (to access the fastq files) is also mentioned in the paper if you wanted to download them.

Cheers,
Ali
