### ISSUE TITLE
Multiple BAMs

### ISSUE THREAD

**Issue by sum732** [gacatag/IntEREst#9]
Hello,
This may be a very trivial questions, but can IntEREst process multiple BAMs at the same time?

I have replicates for WTs and of MUTs and want to get a summary ratio of Intron:Exon across all the replicates of WTs and similarly MUTs. 

Thanks!

**Comment by gacatag** [comment]
Hello @sum732 
No. The `interest()` and `interest.sequential()` functions accept only one input _.bam_ file at a time. In the parallel run the mapped reads within the _.bam_ file are distributed over the computing cores.

For analyzing multiple _.bam_ files you can of course: loop over the individual files, use the relevant _apply_ functions or run several `interest()` runs in separate R sessions, simultaneously.

Cheers!

**Comment by sum732** [comment]
Thanks. Will do the needful to make it work with multiple files.
